name: Slack Notification Build Result
on:
  workflow_call:
    secrets:
      slack_webhook_url:
        required: true
jobs:
  notification:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook_url }}
        if: always()
